#!/usr/bin/python
# encoding:utf-8
# 
# copyright (c) Alex Lee, All rights reserved.

import os
import sys
ModuleRoot = os.path.abspath(os.path.join(__file__, u'../../..'))
if os.path.isdir(ModuleRoot) and not ModuleRoot in sys.path:
    sys.path.append(ModuleRoot)

from xcodeproj.utils import template

REFID_LEN = 24
ARCHIVE_VERSION = 1
OBJECT_VERSION = 50 # xcode 9.3

PBX_ATTR_PREFIX = u'pbx_'

SOURCE_TREE = template.enum(
    group           = u'<group>',
    absolute        = u'<absolute>',
    source_root     = u'SOURCE_ROOT',
    developer_dir   = u'DEVELOPER_DIR',
    built_products_dir = u'BUILT_PRODUCTS_DIR',
    sdkroot         = u'SDKROOT',
)

SOURCE_TREE_VALUES = (
    SOURCE_TREE.group,
    SOURCE_TREE.absolute,
    SOURCE_TREE.source_root,
    SOURCE_TREE.developer_dir,
    SOURCE_TREE.built_products_dir,
    SOURCE_TREE.sdkroot,
)

CONFIG = template.enum (debug = u'Debug', release = u'Release')

PLATFORM = template.enum(
    ios     = u'iOS',
    osx     = u'OSX',
    tvos    = u'tvOS',
    watchos = u'watchOS',
    coress_platform = u'coress_platform'
)

DEFAULT_DEPLOYMENT_TARGET = {
    PLATFORM.ios:   u'8.0',
    PLATFORM.osx:   u'10.12',
}

TARGET_PRODUCT_TYPE = template.enum(
    app         = u'com.apple.product-type.application',
    unit_test   = u'com.apple.product-type.bundle.unit-test',
    app_extension = u'com.apple.product-type.app-extension',
    static_lib  = u'com.apple.product-type.library.static',
    dylib       = u'com.apple.product-type.library.dynamic',
    framework   = u'com.apple.product-type.framework',
    bundle      = u'com.apple.product-type.bundle',
)

LANGUAGE = template.enum(objc=u'Objective-C', swift=u'swift')

MIME_TO_FILETYPE = {
    u'image/jpeg':                  u'image.jpeg',
    u'image/png':                   u'image.png',
    u'application/x-mach-binary':   u'archive.ar',
    u'application/x-archive':       u'archive.ar',
    u'text/plain':                  u'text',
    # u'application/octet-stream':    
}

PRODUCT_FILE_TYPE = (
    u'wrapper.application', 
    u'wrapper.cfbundle', 
    u'wrapper.app-extension', 
    u'wrapper.framework', 
    u'archive.ar')

FILETYPE_BY_EXT = {
    u'.a'                    :u'archive.ar',
    u'.asdictionary'         :u'archive.asdictionary',
    u'.hqx'                  :u'archive.binhex',
    u'.ear'                  :u'archive.ear',
    u'.gz'                   :u'archive.gzip',
    u'.jar'                  :u'archive.jar',
    u'.bin'                  :u'archive.macbinary',
    u'.ppob'                 :u'archive.ppob',
    u'.rsrc'                 :u'archive.rsrc',
    u'.view'                 :u'archive.rsrc',
    u'.sit'                  :u'archive.stuffit',
    u'.tar'                  :u'archive.tar',
    u'.war'                  :u'archive.war',
    u'.zip'                  :u'archive.zip',
    u'.aiff'                 :u'audio.aiff',
    u'.cdda'                 :u'audio.aiff',
    u'.au'                   :u'audio.au',
    u'.midi'                 :u'audio.midi',
    u'.mid'                  :u'audio.midi',
    u'.mp3'                  :u'audio.mp3',
    u'.wav'                  :u'audio.wav',
    u'.data'                 :u'compiled',
    u'.class'                :u'compiled.javaclass',
    u'.dylib'                :u'compiled.mach-o.dylib',
    u'.o'                    :u'compiled.mach-o.objfile',
    u'.rcx'                  :u'compiled.rcx',
    u'.ttf'                  :u'file',
    u'.bdic'                 :u'file',
    u'.stringsdict'          :u'file.bplist',
    u'.storyboard'           :u'file.storyboard',
    u'.uicatalog'            :u'file.uicatalog',
    u'.xib'                  :u'file.xib',
    u'.xcassets'             :u'folder.assetcatalog',
    u'.iconset'              :u'folder.iconset',
    u'.imagecatalog'         :u'folder.imagecatalog',
    u'.bmp'                  :u'image.bmp',
    u'.gif'                  :u'image.gif',
    u'.icns'                 :u'image.icns',
    u'.ico'                  :u'image.ico',
    u'.jpg'                  :u'image.jpeg',
    u'.jpeg'                 :u'image.jpeg',
    u'.pdf'                  :u'image.pdf',
    u'.pict'                 :u'image.pict',
    u'.pct'                  :u'image.pict',
    u'.png'                  :u'image.png',
    u'.tif'                  :u'image.tiff',
    u'.tiff'                 :u'image.tiff',
    u'.md'                   :u'net.daringfireball.markdown',
    u'.mdown'                :u'net.daringfireball.markdown',
    u'.markdown'             :u'net.daringfireball.markdown',
    u'.text'                 :u'net.daringfireball.markdown',
    u'.gyp'                  :u'sourcecode',
    u'.dart'                 :u'sourcecode',
    u'.adb'                  :u'sourcecode.ada',
    u'.ada'                  :u'sourcecode.ada',
    u'.ads'                  :u'sourcecode.ada',
    u'.applescript'          :u'sourcecode.applescript',
    u'.s'                    :u'sourcecode.asm',
    u'.asm'                  :u'sourcecode.asm.asm',
    u'.llx'                  :u'sourcecode.asm.llvm',
    u'.ll'                   :u'sourcecode.asm.llvm',
    u'.c'                    :u'sourcecode.c.c',
    u'.i'                    :u'sourcecode.c.c.preprocessed',
    u'.pch'                  :u'sourcecode.c.h',
    u'.h'                    :u'sourcecode.c.h',
    u'.m'                    :u'sourcecode.c.objc',
    u'.mi'                   :u'sourcecode.c.objc.preprocessed',
    u'.cxx'                  :u'sourcecode.cpp.cpp',
    u'.tcc'                  :u'sourcecode.cpp.cpp',
    u'.cp'                   :u'sourcecode.cpp.cpp',
    u'.cc'                   :u'sourcecode.cpp.cpp',
    u'.cpp'                  :u'sourcecode.cpp.cpp',
    u'.c++'                  :u'sourcecode.cpp.cpp',
    u'.ii'                   :u'sourcecode.cpp.cpp.preprocessed',
    u'.hxx'                  :u'sourcecode.cpp.h',
    u'.h++'                  :u'sourcecode.cpp.h',
    u'.inl'                  :u'sourcecode.cpp.h',
    u'.pch++'                :u'sourcecode.cpp.h',
    u'.hpp'                  :u'sourcecode.cpp.h',
    u'.ipp'                  :u'sourcecode.cpp.h',
    u'.hh'                   :u'sourcecode.cpp.h',
    u'.hp'                   :u'sourcecode.cpp.h',
    u'.mm'                   :u'sourcecode.cpp.objcpp',
    u'.mii'                  :u'sourcecode.cpp.objcpp.preprocessed',
    u'.d'                    :u'sourcecode.dtrace',
    u'.lid'                  :u'sourcecode.dylan',
    u'.dylan'                :u'sourcecode.dylan',
    u'.exp'                  :u'sourcecode.exports',
    u'.for'                  :u'sourcecode.fortran',
    u'.f'                    :u'sourcecode.fortran',
    u'.f77'                  :u'sourcecode.fortran.f77',
    u'.f90'                  :u'sourcecode.fortran.f90',
    u'.f95'                  :u'sourcecode.fortran.f90',
    u'.gsh'                  :u'sourcecode.glsl',
    u'.ctrl'                 :u'sourcecode.glsl',
    u'.vertex'               :u'sourcecode.glsl',
    u'.vs'                   :u'sourcecode.glsl',
    u'.fragment'             :u'sourcecode.glsl',
    u'.fs'                   :u'sourcecode.glsl',
    u'.geom'                 :u'sourcecode.glsl',
    u'.eval'                 :u'sourcecode.glsl',
    u'.vsh'                  :u'sourcecode.glsl',
    u'.geometry'             :u'sourcecode.glsl',
    u'.frag'                 :u'sourcecode.glsl',
    u'.fsh'                  :u'sourcecode.glsl',
    u'.vert'                 :u'sourcecode.glsl',
    u'.gs'                   :u'sourcecode.glsl',
    u'.jam'                  :u'sourcecode.jam',
    u'.java'                 :u'sourcecode.java',
    u'.javascript'           :u'sourcecode.javascript',
    u'.jscript'              :u'sourcecode.javascript',
    u'.js'                   :u'sourcecode.javascript',
    u'.lxx'                  :u'sourcecode.lex',
    u'.lmm'                  :u'sourcecode.lex',
    u'.l'                    :u'sourcecode.lex',
    u'.lpp'                  :u'sourcecode.lex',
    u'.lp'                   :u'sourcecode.lex',
    u'.lm'                   :u'sourcecode.lex',
    u'.mak'                  :u'sourcecode.make',
    u'.gmk'                  :u'sourcecode.make',
    u'.defs'                 :u'sourcecode.mig',
    u'.mig'                  :u'sourcecode.mig',
    u'.map'                  :u'sourcecode.module-map',
    u'.modulemap'            :u'sourcecode.module-map',
    u'.nasm'                 :u'sourcecode.nasm',
    u'.nqc'                  :u'sourcecode.nqc',
    u'.cl'                   :u'sourcecode.opencl',
    u'.inc'                  :u'sourcecode.pascal',
    u'.pas'                  :u'sourcecode.pascal',
    u'.p'                    :u'sourcecode.pascal',
    u'.pp'                   :u'sourcecode.pascal',
    u'.rez'                  :u'sourcecode.rez',
    u'.r'                    :u'sourcecode.rez',
    u'.tbd'                  :u'sourcecode.text-based-dylib-definition',
    u'.ypp'                  :u'sourcecode.yacc',
    u'.yp'                   :u'sourcecode.yacc',
    u'.ymm'                  :u'sourcecode.yacc',
    u'.ym'                   :u'sourcecode.yacc',
    u'.yxx'                  :u'sourcecode.yacc',
    u'.y'                    :u'sourcecode.yacc',
    u'.txt'                  :u'text',
    u'.proto'                :u'text',
    u'.gypi'                 :u'text',
    u'.css'                  :u'text.css',
    u'.htm'                  :u'text.html',
    u'.html'                 :u'text.html',
    u'.rhtml'                :u'text.html.other',
    u'.jsp'                  :u'text.html.other',
    u'.shtml'                :u'text.html.other',
    u'.json'                 :u'text.json',
    u'.1'                    :u'text.man',
    u'.pbxproj'              :u'text.pbxproject',
    u'.dict'                 :u'text.plist',
    u'.plist'                :u'text.plist',
    u'.classdescriptions'    :u'text.plist.ibClassDescription',
    u'.classdescription'     :u'text.plist.ibClassDescription',
    u'.pbfilespec'           :u'text.plist.pbfilespec',
    u'.pblangspec'           :u'text.plist.pblangspec',
    u'.scriptSuite'          :u'text.plist.scriptSuite',
    u'.scriptTerminology'    :u'text.plist.scriptTerminology',
    u'.strings'              :u'text.plist.strings',
    u'.xcbuildrules'         :u'text.plist.xcbuildrules',
    u'.xclangspec'           :u'text.plist.xclangspec',
    u'.xcspec'               :u'text.plist.xcspec',
    u'.xcsynspec'            :u'text.plist.xcsynspec',
    u'.xctxtmacro'           :u'text.plist.xctxtmacro',
    u'.rtf'                  :u'text.rtf',
    u'.csh'                  :u'text.script.csh',
    u'.pm'                   :u'text.script.perl',
    u'.pl'                   :u'text.script.perl',
    u'.perl'                 :u'text.script.perl',
    u'.php'                  :u'text.script.php',
    u'.phtml'                :u'text.script.php',
    u'.php3'                 :u'text.script.php',
    u'.php4'                 :u'text.script.php',
    u'.py'                   :u'text.script.python',
    u'.rb'                   :u'text.script.ruby',
    u'.rbw'                  :u'text.script.ruby',
    u'.sh'                   :u'text.script.sh',
    u'.worksheet'            :u'text.script.worksheet',
    u'.xcconfig'             :u'text.xcconfig',
    u'.archivingdescription' :u'text.xml.ibArchivingDescription',
    u'.codingdescription'    :u'text.xml.ibCodingDescription',
    u'.avi'                  :u'video.avi',
    u'.mpeg'                 :u'video.mpeg',
    u'.mpg'                  :u'video.mpeg',
    u'.qtz'                  :u'video.quartz-composer',
    u'.mov'                  :u'video.quicktime',
    u'.moov'                 :u'video.quicktime',
    u'.appex'                :u'wrapper.app-extension',
    u'.pluginkit'            :u'wrapper.app-extension',
    u'.app'                  :u'wrapper.application',
    u'.xctest'               :u'wrapper.cfbundle',
    u'.octest'               :u'wrapper.cfbundle',
    u'.bundle'               :u'wrapper.cfbundle',
    u'.dsym'                 :u'wrapper.dsym',
    u'.framework'            :u'wrapper.framework',
    u'.htmld'                :u'wrapper.htmld',
    u'.mpkg'                 :u'wrapper.installer-mpkg',
    u'.pkg'                  :u'wrapper.installer-pkg',
    u'.kext'                 :u'wrapper.kernel-extension',
    u'.nib'                  :u'wrapper.nib',
    u'.nib~'                 :u'wrapper.nib',
    u'.xcode'                :u'wrapper.pb-project',
    u'.xcodeproj'            :u'wrapper.pb-project',
    u'.xctarget'             :u'wrapper.pb-target',
    u'.rtfd'                 :u'wrapper.rtfd',
    u'.scnassets'            :u'wrapper.scnassets',
    u'.mdimporter'           :u'wrapper.spotlight-importer',
    u'.xcworkspace'          :u'wrapper.workspace',
    u'.xcdatamodel'          :u'wrapper.xcdatamodel',
    u'.xcdatamodeld'         :u'wrapper.xcdatamodeld',
    u'.xpc'                  :u'wrapper.xpc-service',
}

FOLDER_FILE_TYPE = set([
    u'file.storyboard',
    u'file.uicatalog',
    u'file.xib',
    u'folder.assetcatalog',
    u'folder.iconset',
    u'folder.imagecatalog',
    u'wrapper.app-extension',
    u'wrapper.application',
    u'wrapper.cfbundle',
    u'wrapper.dsym',
    u'wrapper.framework',
    u'wrapper.htmld',
    u'wrapper.installer-mpkg',
    u'wrapper.installer-pkg',
    u'wrapper.kernel-extension',
    u'wrapper.nib',
    u'wrapper.pb-project',
    u'wrapper.pb-target',
    u'wrapper.rtfd',
    u'wrapper.scnassets',
    u'wrapper.spotlight-importer',
    u'wrapper.workspace',
    u'wrapper.xcdatamodel',
    u'wrapper.xcdatamodeld',
    u'wrapper.xpc-service',
])
